using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using CDA.Framework;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;

public class SingletonGenerator
{
    public List<Type> SortedList = new();
    private const string SavePath = "Assets/Scripts/Singleton.txt";
    [MenuItem("Tools/Infrastructure/Generate Singleton Initializer")]
    public static void GenerateSingleton()
    {
        List<Type> sortedList;
        sortedList = GetSortedSingletons();
        if(sortedList == null) return;
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("");
        sb.AppendLine("public static class SingletonInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    public static void InitializeAll()");
        sb.AppendLine("    {");
        sb.AppendLine("        Debug.Log(\"[Core] Start Initialize Singleton Module...\");");

        foreach (var type in sortedList)
        {
            sb.AppendLine($"        {type.Name}.Instance.Init();");
        }

        sb.AppendLine("        Debug.Log(\"[Core] All Singleton Module Initialization Completed!\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        string directory = Path.GetDirectoryName(SavePath);
        if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);
        File.WriteAllText(SavePath, sb.ToString(), Encoding.UTF8);
        
        AssetDatabase.Refresh();
        Debug.Log($"<color=green>Singleton initialization logic generated successfully.: {SavePath}</color>");
    }

    private static List<Type> GetSortedSingletons()
    {
        //1. 获取所有标记了 SingletonAttribute 的类型
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        var singletonTypes = assemblies.SelectMany(s => s.GetTypes())
            .Where(t => t.GetCustomAttribute<CDASingletonAttribute>() != null && !t.IsAbstract)
            .ToList();
        
        //2. 构建依赖关系图
        var resolves = new List<Type>();
        
        var graph = new Dictionary<Type, List<Type>>();
        var inDegree = new Dictionary<Type, int>();
        var priorityMap = new Dictionary<Type, int>();
        
        foreach (var type in singletonTypes)
        {
            if (!graph.ContainsKey(type))
            {
                graph[type] = new List<Type>();
                inDegree[type] = 0;
            }
        }
        
        foreach(var type in singletonTypes)
        {
            var attr = type.GetCustomAttribute<CDASingletonAttribute>();
            priorityMap[type] = attr.Priority;
            foreach (var dep in attr.Dependencies)
            {
                if(!graph.ContainsKey(dep))
                    throw new Exception($"Type {dep.FullName} specified in dependencies of {type.FullName} is not marked with CDASingletonAttribute.");
                graph[dep].Add(type);
                inDegree[type]++;
            }
        }
        
        var priorityQueue = new SortedSet<(int priority, Type type)>(
            Comparer<(int priority, Type type)>.Create((a, b) =>
            {
                int cmp = b.priority.CompareTo(a.priority);
                return cmp != 0 ? cmp : a.type.FullName.CompareTo(b.type.FullName);
            })
        );

        foreach (var kvp in inDegree)
        {
            if(kvp.Value == 0)
                priorityQueue.Add((priorityMap[kvp.Key], kvp.Key));
        }

        while (priorityQueue.Any())
        {
            var curr =  priorityQueue.Min;
            priorityQueue.Remove(curr);
            resolves.Add(curr.type);
            foreach (var neighbor in graph[curr.type])
            {
                inDegree[neighbor]--;
                if (inDegree[neighbor] == 0)
                {
                    priorityQueue.Add((priorityMap[neighbor], neighbor));
                }
            }
        }

        if (resolves.Count != graph.Count)
        {
            throw new Exception($"Exitsting cycles in singleton dependencies");
            return null;
        }
        return resolves;
    }
}